### ISSUE TITLE
Unable to write image on USB drive

### ISSUE THREAD

**Issue by btclinux** [DesobedienteTecnologico/dtails#18]
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/home/user/dtails/./dtails.py", line 110, in <lambda>
    self.connect_button = tk.Button(self.tab3, text="Install to device", state=tk.DISABLED, command=lambda: install_image_to_device(self.pendrive_var.get()))
  File "/home/user/dtails/src/commands.py", line 102, in install_image_to_device
    device = device.split(" - ")[1]
IndexError: list index out of range
```
And please add "Save to img" function) Modified image needs to be saved to file for possibility to install on several drives

**Comment by DesobedienteTecnologico** [comment]
Could you try to do [this steps](https://github.com/DesobedienteTecnologico/dtails/issues/9#issuecomment-1532089516) and give me back the answers?

I will have a look at saving to .img . Thanks for the feedback.

**Comment by DesobedienteTecnologico** [comment]
> And please add "Save to img" function) Modified image needs to be saved to file for possibility to install on several drives

I just remembered that you can flash more times without having to do the whole process from scratch. So you will be able to flash several drives using DTails.

1. Modify [this line](https://github.com/DesobedienteTecnologico/dtails/blob/main/dtails.py#L170) and add there **normal** instead **disabled**.
2. If you have **future_iso** directory (You haven't remove anything) open DTails **Live install** tab and start flashing!
2.1 If you have all removed. Just do the custom process once and then start the flash process in several drives, because you now have enabled the **Live install** tab.

**Comment by btclinux** [comment]
> Could you try to do [this steps](https://github.com/DesobedienteTecnologico/dtails/issues/9#issuecomment-1532089516) and give me back the answers?
> 
> I will have a look at saving to .img . Thanks for the feedback.

1. In dmesg I have a sdb drive, I see "Pendrive connected" in "Live install" tab but not see name of device and /dev/sdX
![изображение](https://github.com/DesobedienteTecnologico/dtails/assets/43704692/3d3400ed-da39-4c73-9d18-ae79e921aa48)
2. The error in first post happens after click on "Install to device"
3. It's a ordinary 8GB USB flash drive

**Comment by DesobedienteTecnologico** [comment]
> > Could you try to do [this steps](https://github.com/DesobedienteTecnologico/dtails/issues/9#issuecomment-1532089516) and give me back the answers?
> > I will have a look at saving to .img . Thanks for the feedback.
> 
>     1. In dmesg I have a sdb drive, I see "Pendrive connected" in "Live install" tab but not see name of device and /dev/sdX
>        ![изображение](https://user-images.githubusercontent.com/43704692/249846685-3d3400ed-da39-4c73-9d18-ae79e921aa48.png)
> 
>     2. The error in first post happens after click on "Install to device"
> 
>     3. It's a ordinary 8GB USB flash drive

Does it shows sdb1, sdb2... in dmesg?
Keep pressing in case it shows up after few seconds.
If pendrive shows there as connected, it should appear in the dropdown menu.

I need to see the dmesg in order to help you. You can put emojis or whatever on top of serial numbers and so if you want.
See [the example here in what I need](https://github.com/DesobedienteTecnologico/dtails/blob/main/dtails.py#L170). Thanks

**Comment by btclinux** [comment]
> > > Could you try to do [this steps](https://github.com/DesobedienteTecnologico/dtails/issues/9#issuecomment-1532089516) and give me back the answers?
> > > I will have a look at saving to .img . Thanks for the feedback.
> > 
> > 
> > ```
> > 1. In dmesg I have a sdb drive, I see "Pendrive connected" in "Live install" tab but not see name of device and /dev/sdX
> >    ![изображение](https://user-images.githubusercontent.com/43704692/249846685-3d3400ed-da39-4c73-9d18-ae79e921aa48.png)
> > 
> > 2. The error in first post happens after click on "Install to device"
> > 
> > 3. It's a ordinary 8GB USB flash drive
> > ```
> 
> Does it shows sdb1, sdb2... in dmesg? Keep pressing in case it shows up after few seconds. If pendrive shows there as connected, it should appear in the dropdown menu.
> 
> I need to see the dmesg in order to help you. You can put emojis or whatever on top of serial numbers and so if you want. See [the example here in what I need](https://github.com/DesobedienteTecnologico/dtails/blob/main/dtails.py#L170). Thanks

Oh, my bad, I choose my drive from list, but there is other issue which I resolved. The issue in that you can't flash to empty drive w/o any file system. If you create a partition then everything fine. If there is no partitions on drive you face with this error:
```
Error: Could not stat device /dev/sd - No such file or directory.
```
