### ISSUE TITLE
Can't choose any connected pen drive

### ISSUE THREAD

**Issue by ZsZolee** [DesobedienteTecnologico/dtails#9]
After the successful build at the Live Install I don't see/can't choose any connected pen drive. At the next restart I see the following error message in the Terminal:

OS: PopOS 22.04 LTS

"
Exception in thread Thread-1 (update_pendrives):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zdesktop/dtails/./dtails.py", line 124, in update_pendrives
    pendrive_dropdown['menu'].add_command(label=pendrive, command=tk._setit(self.pendrive_var, pendrive +" - "+ route))
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
"

**Comment by DesobedienteTecnologico** [comment]
Interesting. I haven't face any issue like that before.

Could you please do the following and write back some information?
1º Open Terminal. Type: `sudo dmesg -w`
2º Connect Pendrive and see something like this:
    
    [ 8882.652390] usb 4-1: new SuperSpeed USB device number 3 using xhci_hcd
    [ 8882.669833] usb 4-1: New USB device found, idVendor=0920, idProduct=6325, bcdDevice= 1.10
    [ 8882.669844] usb 4-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
    [ 8882.669848] usb 4-1: Product: USB FLASH DRIVE
    [ 8882.669851] usb 4-1: Manufacturer: TOSHIBA
    [ 8882.669853] usb 4-1: SerialNumber: 60A44CXXX2345XX5493
    [ 8882.670478] usb-storage 4-1:1.0: USB Mass Storage device detected
    [ 8882.671020] scsi host2: usb-storage 4-1:1.0
    [ 8883.676343] scsi 2:0:0:0: Direct-Access     TOSHIBA  USB FLASH DRIVE  PMAP PQ: 0 ANSI: 6
    [ 8883.676687] sd 2:0:0:0: Attached scsi generic sg0 type 0
    [ 8883.677061] sd 2:0:0:0: [sda] 121995264 512-byte logical blocks: (62.5 GB/58.2 GiB)
    [ 8883.677236] sd 2:0:0:0: [sda] Write Protect is off
    [ 8883.677240] sd 2:0:0:0: [sda] Mode Sense: 45 00 00 00
    [ 8883.677402] sd 2:0:0:0: [sda] Write cache: disabled, read cache: enabled, doesn't support DPO or FUA
    [ 8883.801881]  sda: sda1

See that in my example **I got: Manufacturer: TOSHIBA** and then **[sda]**
#### (Question 1) What did you got?

When you connect your flash device using DTails. Do you get green letters saying that the device is connected? Like:
![image](https://user-images.githubusercontent.com/52879067/235775121-15a141e4-173d-4798-941f-9f7eb9508671.png)

#### (Question 2) Or it stuck on that step?
#### (Question 3) Are you using SSD flash drive?

**Comment by ZsZolee** [comment]
Answer 1:

[23053.218040] usb 2-3: new SuperSpeed USB device number 6 using xhci_hcd
[23053.247255] usb 2-3: New USB device found, idVendor=13fe, idProduct=5500, bcdDevice= 1.10
[23053.247271] usb 2-3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[23053.247279] usb 2-3: Product: USB DISK 3.0
[23053.247285] usb 2-3: Manufacturer:         
[23053.247291] usb 2-3: SerialNumber: 07018A1B06242190
[23053.251263] usb-storage 2-3:1.0: USB Mass Storage device detected
[23053.254373] scsi host5: usb-storage 2-3:1.0
[23054.267880] scsi 5:0:0:0: Direct-Access              USB DISK 3.0     PMAP PQ: 0 ANSI: 6
[23054.268256] sd 5:0:0:0: Attached scsi generic sg4 type 0
[23054.269194] sd 5:0:0:0: [sde] 60555264 512-byte logical blocks: (31.0 GB/28.9 GiB)
[23054.269709] sd 5:0:0:0: [sde] Write Protect is off
[23054.269712] sd 5:0:0:0: [sde] Mode Sense: 45 00 00 00
[23054.270259] sd 5:0:0:0: [sde] Write cache: disabled, read cache: enabled, doesn't support DPO or FUA
[23054.356860]  sde: sde1 sde2 sde3
[23054.357260] sd 5:0:0:0: [sde] Attached SCSI removable disk

Answer 2:

I can't choose anything at that step as I wrote it.

Answer 3:

I'm using a simple 32GB USB 3.0 pen drive.

**Comment by DesobedienteTecnologico** [comment]
Thanks for reply and for this Issue which will help to improve DTails.

I clearly see the problem. The Manufacturer name is empty, and actually we used that to be shown in the dropdown.
https://github.com/DesobedienteTecnologico/dtails/blob/main/dtails.py#L117

I will fix that in a matter of minutes.

**Comment by DesobedienteTecnologico** [comment]
Just fixed @ZsZolee . Please have a try now, and close this Issue if is fixed and fully working.

Regards.

**Comment by ZsZolee** [comment]
Thanks! It's working perfectly!

**Comment by DesobedienteTecnologico** [comment]
> Thanks! It's working perfectly!

Great to ear that!

Enjoy! :)
